### ISSUE TITLE
Not an issue, just a request sorry.

### ISSUE THREAD

**Issue by MobCat** [ChrisMusson/Pogrammable-Doorbell#4]
Add a query tag option for better sharing of doorbell songs.
for eg.
https://chrismusson.github.io/Programmable-Doorbell/?p=21,41,71,91,b3,*22,*43,*73,*72,*93,*73,*22,*33,*23,*02,00&t=fast
or
https://chrismusson.github.io/Programmable-Doorbell/?p=[21,41,71,91,b3,*22,*43,*73,*72,*93,*73,*22,*33,*23,*02,00]&t=fast
don't remember how / if you need to "escape it as a string" or not

Thanks in advanced <3

**Comment by Nixola** [comment]
That "syntax" represents a request to a server, while this application is entirely client-side; what's wrong with the current sharing feature? E.g. https://chrismusson.github.io/Programmable-Doorbell/#fast,21,41,71,91,b3,*22,*43,*73,*72,*93,*73,*22,*33,*23,*02,00  
EDIT: the link can be accessed using the "SHARE" button to the right of the "PLAY" button in the webpage.

**Comment by ChrisMusson** [comment]
I think the idea was to be able to specify a tempo in the shareable link. It is indeed entirely client side so I think just using a regular expression on the URL to capture the tempo if specified would work. If someone wants to implement that, great. If not, I will add it in a few days

**Comment by Nixola** [comment]
The currently shared link does contain the set tempo; it's the first thing in the anchor

**Comment by ChrisMusson** [comment]
Oh yes, you're completely correct, sorry. Then I believe this issue is solved. Thanks!
